In [43]:
import numpy as np
data=np.random.randint(0,10,(3,3))
data


array([[8, 0, 2],
       [4, 9, 6],
       [0, 6, 0]], dtype=int32)

In [44]:
### array creation functions

In [45]:
np.array([1,2,3])#it diplays the array

array([1, 2, 3])

In [46]:
np.zeros((3,3))#t gives the no  of zeroes 

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [47]:
np.ones((3,3))#it gives the no of ones 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [48]:
np.arange(0,10)#it is a loop 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
np.eye(3)#it prints diagonaly of ones

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [50]:
np.linspace(0,20,5)#it divides the array the line spaces condition given 

array([ 0.,  5., 10., 15., 20.])

In [51]:
### Mathematical Functions

In [52]:
dta=np.random.randint(0,100,10)
dta

array([48, 61, 41, 79, 19, 45, 72, 95, 24, 14], dtype=int32)

In [53]:
print(np.sin(dta))
print(np.cos(dta))
print(np.tan(dta))
print(np.arcsin(dta))
print(np.arccos(dta))
print(np.arctan(dta))


[-0.76825466 -0.96611777 -0.15862267 -0.44411267  0.14987721  0.85090352
  0.25382336  0.68326171 -0.90557836  0.99060736]
[-0.64014434 -0.25810164 -0.98733928 -0.89597095  0.98870462  0.52532199
 -0.96725059  0.73017356  0.42417901  0.13673722]
[ 1.20012724  3.74316794  0.1606567   0.49567753  0.15158947  1.61977519
 -0.26241738  0.93575247 -2.1348967   7.24460662]
[nan nan nan nan nan nan nan nan nan nan]
[nan nan nan nan nan nan nan nan nan nan]
[1.54996601 1.55440435 1.54641092 1.55813877 1.51821327 1.54857776
 1.55690833 1.5602704  1.52915375 1.49948886]


C:\Users\Dell\AppData\Local\Temp\ipykernel_12012\2619925843.py:4: RuntimeWarning: invalid value encountered in arcsin
  print(np.arcsin(dta))
C:\Users\Dell\AppData\Local\Temp\ipykernel_12012\2619925843.py:5: RuntimeWarning: invalid value encountered in arccos
  print(np.arccos(dta))


In [54]:
dta

array([48, 61, 41, 79, 19, 45, 72, 95, 24, 14], dtype=int32)

In [55]:
np.log(dta)

array([3.87120101, 4.11087386, 3.71357207, 4.36944785, 2.94443898,
       3.80666249, 4.27666612, 4.55387689, 3.17805383, 2.63905733])

In [56]:
np.log10(100)#100=10^2 so 10 and power 10 cancel theyfore 2 is the answer

np.float64(2.0)

In [57]:
np.log2(4)##4=2^2 so 2 and power 2 cancel theyfore 2 is the answer

np.float64(2.0)

In [58]:
np.e

2.718281828459045

In [59]:
np.log(np.sqrt(2.718281828459045))

np.float64(0.5)

In [60]:
import math 
np.log(math.pow(2.718281828459045,0.2589))

np.float64(0.2589000000000001)

In [61]:
d1=np.random.randint(0,20,(3,3))
d2=np.random.randint(0,20,(3,3))
print(d1)
d2

[[19  7 14]
 [ 2 11  7]
 [17  0  0]]


array([[10,  9, 15],
       [ 3,  6, 12],
       [15,  6, 18]], dtype=int32)

In [ ]:
# d1+d2 or
np.add(d1,d2)

array([[29, 16, 29],
       [ 5, 17, 19],
       [32,  6, 18]], dtype=int32)

In [65]:
np.subtract(d1,d2)

array([[  9,  -2,  -1],
       [ -1,   5,  -5],
       [  2,  -6, -18]], dtype=int32)

In [66]:
np.multiply(d1,d2)

array([[190,  63, 210],
       [  6,  66,  84],
       [255,   0,   0]], dtype=int32)

In [67]:
np.divide(d1,d2)

array([[1.9       , 0.77777778, 0.93333333],
       [0.66666667, 1.83333333, 0.58333333],
       [1.13333333, 0.        , 0.        ]])

In [68]:
d1

array([[19,  7, 14],
       [ 2, 11,  7],
       [17,  0,  0]], dtype=int32)

In [69]:
d2

array([[10,  9, 15],
       [ 3,  6, 12],
       [15,  6, 18]], dtype=int32)

In [75]:
f=np.floor_divide(d1,d2)
f

C:\Users\Dell\AppData\Local\Temp\ipykernel_12012\3643108358.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  f=np.floor_divide(d1,d2)


array([[1, 1, 1],
       [1, 1, 1],
       [1, 0, 0]], dtype=int32)

In [76]:
np.ceil(f)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 0, 0]], dtype=int32)

In [82]:
c=np.divide(d1,d2)
c

C:\Users\Dell\AppData\Local\Temp\ipykernel_12012\2631169947.py:1: RuntimeWarning: invalid value encountered in divide
  c=np.divide(d1,d2)


array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1., nan, nan]])

In [ ]:
np.floor_divide(d1,d2)

C:\Users\Dell\AppData\Local\Temp\ipykernel_12012\1642329175.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  c=np.floor_divide(d1,d2)


array([[1, 1, 1],
       [1, 1, 1],
       [1, 0, 0]], dtype=int32)

In [90]:
c=np.random.randint(0,10,5)/2
print(c)
np.ceil(c)

[2.5 3.5 2.5 2.5 3.5]


array([3., 4., 3., 3., 4.])

In [ ]:
# Mathematical:
#  Arithmetic
#  exponential, log
#  trigonometrics
#  rounding

In [92]:
data=np.random.randint(0,10,10)
data

array([5, 7, 2, 5, 6, 6, 1, 2, 2, 3], dtype=int32)

In [97]:
data[data>5]

array([7, 6, 6], dtype=int32)

In [99]:
marks=np.random.randint(10,100,20)
marks

array([42, 76, 54, 88, 23, 88, 92, 43, 94, 40, 80, 42, 60, 83, 94, 62, 55,
       50, 69, 41], dtype=int32)

In [103]:
print(np.mean(marks))
marks[marks>np.mean(marks)]

63.8


array([76, 88, 88, 92, 94, 80, 83, 94, 69], dtype=int32)

In [101]:
marks[marks<=np.mean(marks)]

array([42, 54, 23, 43, 40, 42, 60, 62, 55, 50, 41], dtype=int32)

In [108]:
d=np.random.randint(10,20,(5,5))
d

array([[16, 19, 11, 17, 11],
       [19, 10, 19, 18, 10],
       [19, 13, 12, 10, 10],
       [16, 12, 15, 12, 14],
       [10, 18, 16, 10, 15]], dtype=int32)

In [ ]:
d.ravel()#it converts rows columns into a flat type in a straight line

array([16, 19, 11, 17, 11, 19, 10, 19, 18, 10, 19, 13, 12, 10, 10, 16, 12,
       15, 12, 14, 10, 18, 16, 10, 15], dtype=int32)

In [ ]:
d.T#it coverts rows to columns and columns to rows such as traves 

array([[16, 19, 19, 16, 10],
       [19, 10, 13, 12, 18],
       [11, 19, 12, 15, 16],
       [17, 18, 10, 12, 10],
       [11, 10, 10, 14, 15]], dtype=int32)

In [120]:
data=np.random.randint(0,10,20)
print(data)
data.reshape(4,5)

[2 7 0 1 9 6 5 7 3 3 6 9 2 4 5 8 5 2 4 1]


array([[2, 7, 0, 1, 9],
       [6, 5, 7, 3, 3],
       [6, 9, 2, 4, 5],
       [8, 5, 2, 4, 1]], dtype=int32)

In [121]:
d1

array([[19,  7, 14],
       [ 2, 11,  7],
       [17,  0,  0]], dtype=int32)

In [122]:
d2

array([[19,  7, 14],
       [ 2, 11,  7],
       [17,  0,  0]], dtype=int32)

In [125]:
np.hstack([d1,d2])

array([[19,  7, 14, 19,  7, 14],
       [ 2, 11,  7,  2, 11,  7],
       [17,  0,  0, 17,  0,  0]], dtype=int32)

In [126]:
np.vstack([d1,d2])

array([[19,  7, 14],
       [ 2, 11,  7],
       [17,  0,  0],
       [19,  7, 14],
       [ 2, 11,  7],
       [17,  0,  0]], dtype=int32)

In [131]:
data=np.random.randint(0,10,10)
np.split(data,5)

[array([3, 0], dtype=int32),
 array([8, 4], dtype=int32),
 array([4, 0], dtype=int32),
 array([8, 3], dtype=int32),
 array([4, 1], dtype=int32)]

In [136]:
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8]])

In [138]:
np.hsplit(matrix,2)

[array([[1, 2],
        [5, 6]]),
 array([[3, 4],
        [7, 8]])]

In [139]:
np.hsplit(matrix,4)

[array([[1],
        [5]]),
 array([[2],
        [6]]),
 array([[3],
        [7]]),
 array([[4],
        [8]])]

In [142]:
np.vsplit(matrix,2)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]

In [ ]:
np.vsplit(matrix,1)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]])]

In [146]:
matrix1 = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])

In [ ]:
np.vsplit(matrix1,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [161]:
np.vsplit(matrix1,[1,3])

[array([[1, 2, 3, 4]]),
 array([[ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]])]