In [1]:
import numpy as np
data=np.random.randint(0,10,10)
data

array([0, 9, 7, 7, 4, 4, 9, 1, 3, 7], dtype=int32)

In [7]:
np.quantile(data,0.25)

np.float64(3.25)

In [8]:
np.quantile(data,0.5)

np.float64(5.0)

In [14]:
np.quantile(data,0.75)

np.float64(6.75)

In [16]:
data=np.random.randint(0,10,(3,3))
data

array([[3, 0, 0],
       [3, 1, 5],
       [0, 6, 2]], dtype=int32)

In [17]:
np.corrcoef(data)

array([[ 1.        ,  0.        , -0.75592895],
       [ 0.        ,  1.        , -0.65465367],
       [-0.75592895, -0.65465367,  1.        ]])

In [4]:
np.loadtxt("D:\DATA SCIENCE\PYTHON\TXT.csv",delimiter=',',skiprows=1)

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
C:\Users\Dell\AppData\Local\Temp\ipykernel_1244\4089633100.py:1: SyntaxWarning: invalid escape sequence '\D'
  np.loadtxt("D:\DATA SCIENCE\PYTHON\TXT.csv",delimiter=',',skiprows=1)


array([[40., 26., 27., 27.],
       [30., 31., 35., 25.],
       [28., 35., 38., 30.],
       [24., 30., 29., 40.],
       [29., 22., 36., 22.],
       [25., 33., 21., 37.],
       [30., 33., 38., 38.],
       [29., 29., 22., 29.],
       [22., 23., 37., 29.],
       [35., 21., 21., 37.],
       [20., 21., 29., 30.],
       [27., 25., 29., 40.],
       [36., 26., 33., 30.],
       [29., 39., 29., 29.],
       [25., 26., 21., 28.],
       [36., 40., 31., 21.],
       [32., 21., 26., 34.],
       [39., 33., 36., 22.],
       [35., 24., 39., 29.]])

In [6]:
data=np.random.randint(10,200,(4,6))
data


array([[142, 182, 169, 192, 106,  79],
       [ 89,  77,  79, 196, 135, 159],
       [ 80, 159,  25,  87, 118, 151],
       [125, 120,  33,  62, 159, 131]], dtype=int32)

In [7]:
np.save("array.npy",data)

In [8]:
np.load("array.npy")

array([[142, 182, 169, 192, 106,  79],
       [ 89,  77,  79, 196, 135, 159],
       [ 80, 159,  25,  87, 118, 151],
       [125, 120,  33,  62, 159, 131]], dtype=int32)

In [22]:
arr=np.fromstring('1 2 3 4 6',sep=" ",dtype=float)
arr

array([1., 2., 3., 4., 6.])

In [30]:
arr=np.fromstring('1\t2\t3\t4\t6',sep="\t",dtype=float)
print(arr)

[1. 2. 3. 4. 6.]


In [32]:
arr=np.fromstring('1 2 3 4 6',sep=" ",count=3)
print(arr)

[1. 2. 3.]


In [40]:
txt=open("D:\DATA SCIENCE\PYTHON\sm.txt")
txt.read()

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
C:\Users\Dell\AppData\Local\Temp\ipykernel_1244\1267399388.py:1: SyntaxWarning: invalid escape sequence '\D'
  txt=open("D:\DATA SCIENCE\PYTHON\sm.txt")


'sample\nsample\n\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\n'

In [47]:
txt.seek(0)#it tells again you read from first and print
txt.read()

'sample\nsample\n\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\nsample\n'

In [ ]:
txt.seek(0)
txt.read().splitlines()#it gives line by line

['sample',
 'sample',
 '',
 'sample',
 'sample',
 'sample',
 'sample',
 'sample',
 'sample',
 'sample',
 'sample',
 'sample',
 'sample',
 'sample',
 'sample',
 'sample',
 'sample',
 'sample',
 'sample',
 'sample',
 'sample',
 'sample',
 'sample',
 'sample',
 'sample',
 'sample',
 'sample',
 'sample',
 'sample',
 'sample',
 'sample',
 'sample',
 'sample',
 'sample',
 'sample',
 'sample',
 'sample',
 'sample',
 'sample',
 'sample',
 'sample',
 'sample',
 'sample',
 'sample',
 'sample',
 'sample',
 'sample',
 'sample',
 'sample',
 'sample',
 'sample']

In [ ]:
| Mode  | Meaning                  | Can Read? | Can Write? | File Created if Missing? |
|-------|--------------------------|-----------|------------|--------------------------|
| r   | Read text                 | ✅        | ❌         | ❌                       |
| w   | Write text (overwrite)    | ❌        | ✅         | ✅                       |
| a   | Append text               | ❌        | ✅         | ✅                       |
| r+  | Read + write              | ✅        | ✅         | ❌                       |
| rb  | Read binary               | ✅        | ❌         | ❌                       |
| wb  | Write binary              | ❌        | ✅         | ✅                       |

In [16]:
with open("f.txt",'w') as file:
    file.write("DATA SCIENCES")#IT IS USED TO WRITE INSIDE THE FILE

In [17]:
with open("f.txt",'r') as file:
    content=file.read()
    print(content)

DATA SCIENCES


In [18]:
with open("f.txt",'a') as file:
    file.write("first code\n")
    file.write("second code\n")
    file.write("third code\n")



In [19]:
with open("f.txt",'r') as file:
    content=file.read()
    print(content)

DATA SCIENCESfirst code
second code
third code



In [29]:
with open("f.txt",'r+') as f:
    text=f.read()
    f.seek(0)
    f.write("upadted contenet "+text)


In [32]:
with open("f.txt",'r') as f:
    print(f.read())

upadted contenet upadted contenet upadted contenet t code
second code
third code



In [ ]:
import PyPDF2
with open("","rb") as f:
    reader=PyPDF2.PdfReader(f)
    print("no of pages in the pdf",len(reader.pages))

    page=reader.pages[0]
    txt=page.extract_text()
    print(txt)


<>:2: SyntaxWarning: invalid escape sequence '\D'
<>:2: SyntaxWarning: invalid escape sequence '\D'
C:\Users\Dell\AppData\Local\Temp\ipykernel_11284\3945793782.py:2: SyntaxWarning: invalid escape sequence '\D'
  with open("D:\DATA SCIENCE\PYTHON\3BR22CS403_Provisional_Grade_Card.pdf","rb") as f:
C:\Users\Dell\AppData\Local\Temp\ipykernel_11284\3945793782.py:2: SyntaxWarning: invalid escape sequence '\D'
  with open("D:\DATA SCIENCE\PYTHON\3BR22CS403_Provisional_Grade_Card.pdf","rb") as f:


OSError: [Errno 22] Invalid argument: 'D:\\DATA SCIENCE\\PYTHON\x03BR22CS403_Provisional_Grade_Card.pdf'