In [5]:
import numpy as np
type(np.array([1,2,3]))


numpy.ndarray

In [7]:
data=np.random.randint(1,200,(5,5))
data

array([[174,  57, 147,  22,  55],
       [ 60,  91, 137,  99, 103],
       [162, 142,  92,  52,  80],
       [ 50,  58, 171,  33, 191],
       [ 62,  65, 103,  66,   8]], dtype=int32)

In [10]:
print(data[0,0])
print(data[-3:-1,-3:-1])
print(data[-2:-1,-2:-1])


174
[[ 92  52]
 [171  33]]
[[33]]


In [12]:
x=[1,2,3]#these is list data type               
print(type(x))
y=np.array([1,2,3])# numpy array data type
print(type(y))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
#list vs np array differences 
#1st one is we can't divide for performe opearation directly in list but in np arrary we can
# x/2 error occered
y/2#it perfoms operation all at onces beacuse it designed for that

array([0.5, 1. , 1.5])

In [ ]:
#2nd one is in list float remains float but in numpy all the elements are float
x=[1,2,3,6.0]
y=np.array([1,2,3,6.0])
print(x)
print(y)#it ascpect to have all same data type it changes when in the array which has highest data type

[1, 2, 3, 6.0]
[1. 2. 3. 6.]


In [ ]:
y=[1,2,3,"data"]#data type changes as per the highest priority of data atype
y

[1, 2, 3, 'data']

In [ ]:
#performanes type np array is better  it use backend as c programming lang and it is memory efficient it stores the same data type where as compared to list it stores every element of different data type soo

In [ ]:
#3d one 
#list->hetrogenous element as different data type
#numpy->omogenous as same data type

In [ ]:
#random family functions
#radnomly generate integer numbers

In [21]:
np.random.randint(0,100,(5,5))

array([[65, 88, 29, 87, 80],
       [70, 27, 57, 42, 57],
       [75, 89,  6, 23, 97],
       [90, 16, 61, 48, 48],
       [28, 76, 74,  9, 72]], dtype=int32)

In [ ]:
np.random.rand(3,3)
#it always fallow range 0 to 1

array([[0.21838366, 0.26972735, 0.78250347],
       [0.939789  , 0.8694213 , 0.06718863],
       [0.00376329, 0.13187935, 0.68539606]])

In [ ]:
#normalization or ,min max dara
data=np.array([1,2,3,4])
(data-data.min())/(data.max()-data.min())

array([0.        , 0.33333333, 0.66666667, 1.        ])