In [2]:
import numpy as np

# Manually created array: [Store ID, Sales, Customers, Inventory, Returns]
retail_data = np.array([
    [1, 25000, 300, 1200, 10],
    [2, 32000, 450, 1500, 15],
    [3, 28000, 380, 1100, 8],
    [4, 41000, 500, 1600, 20],
    [5, 35000, 420, 1400, 12],
    [6, 27000, 360, 1300, 9],
    [7, 39000, 480, 1700, 18],
    [8, 30000, 400, 1250, 14],
    [9, 45000, 550, 1800, 25],
    [10, 33000, 410, 1450, 11]
])

print(retail_data)
print("[Store ID, Sales, Customers, Inventory, Returns] ")

[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]
[Store ID, Sales, Customers, Inventory, Returns] 


In [ ]:
# Retail Data – Business Questions (for `retail_data`)

**Assumed columns:** `[StoreID, Sales, Customers, Inventory, Returns]`

## Basic Performance Analysis
1. What is the **total revenue** generated across all stores?
2. Which store recorded the **highest sales**?
3. Which store recorded the **lowest sales**?
4. What is the **average daily sales** per store?
5. How many stores achieved sales **above ₹35,000**?

## Customer Insights
6. Which store had the **highest customer footfall**?
7. What is the **average number of customers** per store?
8. How many stores have **more than 450 customers**?
9. Which store has the **lowest customer count**?
10. Is there any store where **high sales do not correspond to high customers**?

## Inventory & Returns Analysis
11. What is the **total inventory** across all stores?
12. Which store has the **highest inventory stock**?
13. How many stores have **inventory less than 1300 units**?
14. Which store has the **highest return rate** (returns ÷ inventory)?
15. Which stores have **returns greater than 15 units**?

## Sales & Customer Correlation
16. Is there a **positive correlation** between sales and customers?
17. Which store has **high customer visits but low sales**?
18. Which store has **low customers but high sales**?
19. How many stores have **sales per customer above ₹90**?
20. Which stores could **benefit from customer acquisition campaigns** (low customers, high inventory)?

## Profitability & Growth
21. If profit margin is **20% of sales**, what is the **profit per store**?
22. Which store has the **highest profit**?
23. Which store has the **lowest profit**?
24. If sales increase by **10% next month**, what are the **new sales figures**?
25. How will **total profit** change with the 10% sales increase?

## Operational Strategy
26. Which stores need **inventory restocking** based on sales and current stock?
27. Which stores show **high returns percentage** and might require **quality checks**?
28. Which store is the **best performer overall** (sales, customers, inventory turnover)?
29. Which store is the **worst performer overall**?
30. Which stores can be considered for **expansion** based on strong sales and customer metrics?


In [ ]:
## Basic Performance Analysis
1. What is the **total revenue** generated across all stores?
2. Which store recorded the **highest sales**?
3. Which store recorded the **lowest sales**?
4. What is the **average daily sales** per store?
5. How many stores achieved sales **above ₹35,000**?


In [4]:
# 1. What is the **total revenue** generated across all stores?
retail_data[:,1].sum()

np.int64(335000)

In [5]:
# 2.Which store recorded the **highest sales**?
retail_data[:,1].argmax()+1

np.int64(9)

In [8]:
# 3.Which store recorded the **lowest sales**?
retail_data[:,1].argmin()+1

np.int64(1)

In [14]:
# 4. What is the **average daily sales** per store?
avg=retail_data[:,1].mean()
avg


np.float64(33500.0)

In [15]:
# 5.How many stores achieved sales **above ₹35,000**?
retail_data[:,1]>35000

array([False, False, False,  True, False, False,  True, False,  True,
       False])

In [ ]:
## Customer Insights
6. Which store had the **highest customer footfall**?
7. What is the **average number of customers** per store?
8. How many stores have **more than 450 customers**?
9. Which store has the **lowest customer count**?
10. Is there any store where **high sales do not correspond to high customers**?

In [26]:
# 6. Which store had the **highest customer footfall**?
retail_data[:,2].argmax()+1

np.int64(9)

In [28]:
# 7. What is the **average number of customers** per store?
avg=retail_data[:,2].mean()
avg

np.float64(425.0)

In [31]:
# 8. How many stores have **more than 450 customers**?
retail_data[:,2]>450


array([False, False, False,  True, False, False,  True, False,  True,
       False])

In [34]:
# 9. Which store has the **lowest customer count**?
retail_data[:,2].argmin()+1


np.int64(1)

In [43]:
# 10. Is there any store where **high sales do not correspond to high customers**?
a = retail_data[:,1].mean()
b = retail_data[:,2].mean()
res = retail_data[(retail_data[:,1] > a) & (retail_data[:,2]< b)]
res

array([[    5, 35000,   420,  1400,    12]])

In [ ]:
## Inventory & Returns Analysis
11. What is the **total inventory** across all stores?
12. Which store has the **highest inventory stock**?
13. How many stores have **inventory less than 1300 units**?
14. Which store has the **highest return rate** (returns ÷ inventory)?
15. Which stores have **returns greater than 15 units**?


In [45]:
# 11. What is the **total inventory** across all stores?
retail_data[:,3].sum()

np.int64(14300)

In [47]:
# Which store has the **highest inventory stock**?
retail_data[:,3].argmax()+1

np.int64(9)

In [48]:
# 13. How many stores have **inventory less than 1300 units**?
retail_data[retail_data[:,3]<1300]

array([[    1, 25000,   300,  1200,    10],
       [    3, 28000,   380,  1100,     8],
       [    8, 30000,   400,  1250,    14]])

In [51]:
# 14. Which store has the **highest return rate** (returns ÷ inventory)?
high=retail_data[:,4]/retail_data[:,3]
retail_data[high.argmax()]

array([    9, 45000,   550,  1800,    25])

In [53]:
# Which stores have **returns greater than 15 units**?
retail_data[retail_data[:,4]>15]

array([[    4, 41000,   500,  1600,    20],
       [    7, 39000,   480,  1700,    18],
       [    9, 45000,   550,  1800,    25]])

In [ ]:
## Sales & Customer Correlation
16. Is there a **positive correlation** between sales and customers?
17. Which store has **high customer visits but low sales**?
18. Which store has **low customers but high sales**?
19. How many stores have **sales per customer above ₹90**?
20. Which stores could **benefit from customer acquisition campaigns** (low customers, high inventory)?

In [57]:
# 16. Is there a **positive correlation** between sales and customers?
s=retail_data[:,1]
c=retail_data[:,2]
np.corrcoef(s,c)[0,1]


np.float64(0.9593636912502479)

In [66]:
# Which store has **high customer visits but low sales**?
a=retail_data[:,2].mean()
b=retail_data[:,1].mean()
res=retail_data[(retail_data[:,2]>a)& (retail_data[:,1]<b)]
res

array([[    2, 32000,   450,  1500,    15]])

In [69]:
# Which store has **low customers but high sales**?
a
b
retail_data[(retail_data[:,2]<a) & (retail_data[:,1]>b)]

array([[    5, 35000,   420,  1400,    12]])

In [83]:
# 19. How many stores have **sales per customer above ₹90**?
s=retail_data[:,1]/retail_data[:,2]
# (s>90).sum()
retail_data[s>90]

array([], shape=(0, 5), dtype=int64)

In [86]:
# 20. Which stores could **benefit from customer acquisition campaigns** (low customers, high inventory)?
c=retail_data[:,2].mean()
i=retail_data[:,3].mean()
res=retail_data[(retail_data[:,2]<c) &(retail_data[:,3]>i)]
res

array([[   10, 33000,   410,  1450,    11]])

In [ ]:
## Profitability & Growth
21. If profit margin is **20% of sales**, what is the **profit per store**?
22. Which store has the **highest profit**?
23. Which store has the **lowest profit**?
24. If sales increase by **10% next month**, what are the **new sales figures**?
25. How will **total profit** change with the 10% sales increase?

In [108]:
# 21. If profit margin is **20% of sales**, what is the **profit per store**?
retail_data[:,1]*0.2

array([5000., 6400., 5600., 8200., 7000., 5400., 7800., 6000., 9000.,
       6600.])

In [113]:
# 22. Which store has the **highest profit**?
s=retail_data[:,1]*0.2
np.argmax(s)+1

np.int64(9)

In [114]:
# 23. Which store has the **lowest profit**?
s=retail_data[:,1]*0.2
np.argmin(s)+1

np.int64(1)

In [131]:
# 24. If sales increase by **10% next month**, what are the **new sales figures**?

old=retail_data[:,1]
inc=old*0.10
new=old+inc
new


array([27500., 35200., 30800., 45100., 38500., 29700., 42900., 33000.,
       49500., 36300.])

In [138]:
# 25. How will **total profit** change with the 10% sales increase?
old=retail_data[:,1]*0.2
inc=old*0.1
new=old+inc
print(new)
x=sum(old)
print(x)
y=sum(new)
print(y)
print(y-x)


[5500. 7040. 6160. 9020. 7700. 5940. 8580. 6600. 9900. 7260.]
67000.0
73700.0
6700.0


In [ ]:
## Operational Strategy
26. Which stores need **inventory restocking** based on sales and current stock?
27. Which stores show **high returns percentage** and might require **quality checks**?
28. Which store is the **best performer overall** (sales, customers, inventory turnover)?
29. Which store is the **worst performer overall**?
30. Which stores can be considered for **expansion** based on strong sales and customer metrics?

In [146]:
# 26. Which stores need **inventory restocking** based on sales and current stock?
s=retail_data[:,1].mean()
i=retail_data[:,3].mean()
retail_data[(retail_data[:,1]>s) & (retail_data[:,3]<i)]

array([[    5, 35000,   420,  1400,    12]])

In [155]:
# 27. Which stores show **high returns percentage** and might require **quality checks**?
r=(retail_data[:,4]/retail_data[:,1])*100
m=r.mean()
retail_data[r>m]



array([[    2, 32000,   450,  1500,    15],
       [    4, 41000,   500,  1600,    20],
       [    7, 39000,   480,  1700,    18],
       [    8, 30000,   400,  1250,    14],
       [    9, 45000,   550,  1800,    25]])

In [165]:
# 28. Which store is the **best performer overall** (sales, customers, inventory turnover)?
s=retail_data[:,1]/retail_data[:,1].max()
c=retail_data[:,2]/retail_data[:,2].max()
turn=retail_data[:,1]/retail_data[:,3]
tscore=turn/retail_data[:,3].max()

best=s+c+tscore
best_score=np.argmax(best)
print("the best store is",int(retail_data[best_score,0]))
# print("Best performer store ID:", int(retail_data[best_store_index, 0]))

the best store is 9


In [167]:
# 29. Which store is the **worst performer overall**?
s=retail_data[:,1]/retail_data[:,1].max()
c=retail_data[:,2]/retail_data[:,2].max()
turn=retail_data[:,1]/retail_data[:,3]
tscore=turn/retail_data[:,3].max()
best=s+c+tscore
best_score=np.argmin(best)
print("the worste store is",int(retail_data[best_score,0]))



the worste store is 1


In [179]:
# 30. Which stores can be considered for **expansion** based on strong sales and customer metrics?
s=retail_data[:,1].mean()
c=retail_data[:,2].mean()
res=retail_data[(retail_data[:,1]>s) & (retail_data[:,2]>c)]
res


array([[    4, 41000,   500,  1600,    20],
       [    7, 39000,   480,  1700,    18],
       [    9, 45000,   550,  1800,    25]])