In [6]:
import numpy as np


In [4]:
data=np.random.randint(0,10,(3,3))
data

array([[5, 9, 0],
       [3, 0, 9],
       [8, 9, 8]], dtype=int32)

In [ ]:
np.mean(data)#mean means average

np.float64(5.666666666666667)

In [ ]:
# np.mean
# std
# var
# np.median

In [15]:
np.random.randn(30,30).mean()

np.float64(0.0010680977727445936)

In [16]:
data

array([[5, 9, 0],
       [3, 0, 9],
       [8, 9, 8]], dtype=int32)

In [17]:
np.std(data)

np.float64(3.5901098714230026)

In [20]:
np.mean(data)

np.float64(5.666666666666667)

In [23]:
np.median(data)

np.float64(8.0)

In [8]:
data=np.random.randint(0,100,10)
data

array([59, 17, 96, 28, 94, 21, 51, 14, 40, 68], dtype=int32)

In [9]:
data.min()

np.int32(14)

In [10]:
data.max()

np.int32(96)

In [11]:
print(data.min()-data.max())

-82


In [13]:
data.argmax()

np.int64(2)

In [15]:
np.argmin(data)

np.int64(7)

In [23]:
s=data.reshape((2,5))
s

array([[59, 17, 96, 28, 94],
       [21, 51, 14, 40, 68]], dtype=int32)

In [25]:

s.max(axis=0)

array([59, 51, 96, 40, 94], dtype=int32)

In [26]:
s.max(axis=1)

array([96, 68], dtype=int32)

In [27]:
s.min(axis=1)

array([17, 14], dtype=int32)

In [29]:
s.min(axis=0)

array([21, 17, 14, 28, 68], dtype=int32)

In [ ]:
data=np.random.randint(0,100,(3,3))
data

array([[35, 74, 28],
       [27, 12, 41],
       [ 1,  8, 85]], dtype=int32)

In [55]:
data[-2:,-2:].max()

np.int32(85)

In [58]:
import numpy as np

# Manually created array: [Store ID, Sales, Customers, Inventory, Returns]
retail_data = np.array([
    [1, 25000, 300, 1200, 10],
    [2, 32000, 450, 1500, 15],
    [3, 28000, 380, 1100, 8],
    [4, 41000, 500, 1600, 20],
    [5, 35000, 420, 1400, 12],
    [6, 27000, 360, 1300, 9],
    [7, 39000, 480, 1700, 18],
    [8, 30000, 400, 1250, 14],
    [9, 45000, 550, 1800, 25],
    [10, 33000, 410, 1450, 11]
])

print(retail_data)
#[Store ID, Sales, Customers, Inventory, Returns]

[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]


In [ ]:
#what is the sales happended in all the stores 
retail_data[:,1].sum()

array([45.45454545, 58.18181818, 50.90909091, 74.54545455, 63.63636364,
       49.09090909, 70.90909091, 54.54545455, 81.81818182, 60.        ])

In [64]:
#which store has highest inventory 
retail_data[:,3].argmax()+1

np.int64(9)

In [ ]:
# sales/customer
# sales/transaction : basket value
# sales/units: basket size

In [80]:
#which store has highest sale per customer
f=retail_data[:,1]/retail_data[:,2]
print(np.argmax(f)+1)

1


In [ ]:
# Retail Data – Business Questions (for `retail_data`)

**Assumed columns:** `[StoreID, Sales, Customers, Inventory, Returns]`

## Basic Performance Analysis
1. What is the **total revenue** generated across all stores?
2. Which store recorded the **highest sales**?
3. Which store recorded the **lowest sales**?
4. What is the **average daily sales** per store?
5. How many stores achieved sales **above ₹35,000**?

## Customer Insights
6. Which store had the **highest customer footfall**?
7. What is the **average number of customers** per store?
8. How many stores have **more than 450 customers**?
9. Which store has the **lowest customer count**?
10. Is there any store where **high sales do not correspond to high customers**?

## Inventory & Returns Analysis
11. What is the **total inventory** across all stores?
12. Which store has the **highest inventory stock**?
13. How many stores have **inventory less than 1300 units**?
14. Which store has the **highest return rate** (returns ÷ inventory)?
15. Which stores have **returns greater than 15 units**?

## Sales & Customer Correlation
16. Is there a **positive correlation** between sales and customers?
17. Which store has **high customer visits but low sales**?
18. Which store has **low customers but high sales**?
19. How many stores have **sales per customer above ₹90**?
20. Which stores could **benefit from customer acquisition campaigns** (low customers, high inventory)?

## Profitability & Growth
21. If profit margin is **20% of sales**, what is the **profit per store**?
22. Which store has the **highest profit**?
23. Which store has the **lowest profit**?
24. If sales increase by **10% next month**, what are the **new sales figures**?
25. How will **total profit** change with the 10% sales increase?

## Operational Strategy
26. Which stores need **inventory restocking** based on sales and current stock?
27. Which stores show **high returns percentage** and might require **quality checks**?
28. Which store is the **best performer overall** (sales, customers, inventory turnover)?
29. Which store is the **worst performer overall**?
30. Which stores can be considered for **expansion** based on strong sales and customer metrics?


In [82]:
d=np.random.randint(0,10,5)
d

array([6, 1, 9, 7, 2], dtype=int32)

In [83]:
x=10

In [84]:
d+x

array([16, 11, 19, 17, 12], dtype=int32)

In [86]:
x=np.random.randint(1,10,(3,1))
x

array([[2],
       [3],
       [1]], dtype=int32)

In [92]:
y=np.random.randint(1,10,(1,3))
y

array([[5, 5, 1]], dtype=int32)

In [93]:
print(x+y)

[[7 7 3]
 [8 8 4]
 [6 6 2]]
